name: "💡 Feature Request"
description: "Create a new issue for a feature request"
title: "💡 "
labels: [
  "enhancement"
]
body:
  - type: dropdown
    id: type
    attributes:
      label: "Type"
      description: What type of request is this?
      multiple: false
      options:
        - Add or change a tool in the images
        - Automation enhancement (pipeline/build/package)
        - Documentation
        - Something else
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues"
      description: Common issues
      placeholder: "#Issues IDs"
    validations:
      required: false
  - type: textarea
    id: implementation_pr
    attributes:
      label: "Implementation PR"
      description: Is there a PR for this? Link it here...
      placeholder: "#Pull Request ID"
    validations:
      required: false
