FROM ubuntu:latest

ARG TARGETPLATFORM

RUN apt update -yq && \
  apt upgrade -yq && \
  apt install -yq --no-install-recommends --no-install-suggests \
  ca-certificates \
  apt-transport-https \
  wget \
  curl \
  bash \
  jq \
  figlet \
  unzip \
  zip \
  git \
  shellcheck \
  nano \
  tar \
  rm -rf /var/lib/apt/lists/*

# Install languages, libraries and frameworks
RUN apt install -yq --no-install-recommends --no-install-suggests \
  nodejs \
  npm \
  python3 \
  python3-pip \
  golang && \
  rm -rf /var/lib/apt/lists/*

# Install terraform (https://github.com/hashicorp/terraform)
RUN export tfrelease="$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/hashicorp/terraform/releases/latest | awk -F / '{print substr($NF,2);}')" \
  && case ${TARGETPLATFORM} in \
  "linux/arm64")  ARCHITECTURE=arm64  ;; \
  *)              ARCHITECTURE=amd64   ;; \
  esac \
  && echo "Installing terraform v${tfrelease} (${ARCHITECTURE})" \
  && wget https://releases.hashicorp.com/terraform/${tfrelease}/terraform_${tfrelease}_linux_${ARCHITECTURE}.zip \
  && unzip terraform_${tfrelease}_linux_${ARCHITECTURE}.zip \
  && chmod +x terraform \
  && mv terraform /usr/local/bin/terraform \
  && rm terraform_${tfrelease}_linux_${ARCHITECTURE}.zip

# Install atmos (https://github.com/cloudposse/atmos)
RUN export atmosrelease="$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/cloudposse/atmos/releases/latest | awk -F / '{print substr($NF,2);}')" \
  && case ${TARGETPLATFORM} in \
  "linux/arm64")  ARCHITECTURE=arm64  ;; \
  *)              ARCHITECTURE=amd64   ;; \
  esac \
  && echo "Installing atmos v${atmosrelease} (${ARCHITECTURE})" \
  && wget https://github.com/cloudposse/atmos/releases/download/v${atmosrelease}/atmos_${atmosrelease}_linux_${ARCHITECTURE} \
  && chmod +x atmos_${atmosrelease}_linux_${ARCHITECTURE} \
  && mv atmos_${atmosrelease}_linux_${ARCHITECTURE} /usr/local/bin/atmos

# Install tflint (https://github.com/terraform-linters/tflint)
RUN export tflintrelease="$(curl -Ls -o /dev/null -w %{url_effective} "https://github.com/terraform-linters/tflint/releases/latest" | awk -F / '{print substr($NF,2);}')" \
  && case ${TARGETPLATFORM} in \
  "linux/arm64")  ARCHITECTURE=arm64  ;; \
  *)              ARCHITECTURE=amd64   ;; \
  esac \
  && echo "Installing tflint v${tflintrelease} (${ARCHITECTURE})" \
  && wget https://github.com/terraform-linters/tflint/releases/download/v${tflintrelease}/tflint_linux_${ARCHITECTURE}.zip \
  && unzip -d /usr/local/bin tflint_linux_${ARCHITECTURE}.zip \
  && chmod +x /usr/local/bin/tflint \
  && rm tflint_linux_${ARCHITECTURE}.zip

# Install tfsec (https://github.com/aquasecurity/tfsec)
RUN export tfsecrelease="$(curl -Ls -o /dev/null -w %{url_effective} "https://github.com/aquasecurity/tfsec/releases/latest" | awk -F / '{print substr($NF,2);}')" \
  && case ${TARGETPLATFORM} in \
  "linux/arm64")  ARCHITECTURE=arm64  ;; \
  *)              ARCHITECTURE=amd64   ;; \
  esac \
  && echo "Installing tfsec v${tfsecrelease} (${ARCHITECTURE})" \
  && wget https://github.com/aquasecurity/tfsec/releases/download/v${tfsecrelease}/tfsec-linux-${ARCHITECTURE} \
  && chmod +x tfsec-linux-${ARCHITECTURE} \
  && mv tfsec-linux-${ARCHITECTURE} /usr/local/bin/tfsec

# Install Open Policy Agent (https://openpolicyagent.org)
RUN case ${TARGETPLATFORM} in \
  "linux/arm64")  ARCHITECTURE=arm64  ;; \
  *)              ARCHITECTURE=amd64   ;; \
  esac \
  && echo "Installing opa (${ARCHITECTURE})" \
  && curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_${ARCHITECTURE}_static \
  && chmod +x opa \
  && mv opa /usr/local/bin/opa

# Install terraform-docs
RUN export tfdocsrelease="$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/terraform-docs/terraform-docs/releases/latest | awk -F / '{print substr($NF,2);}')" \
  && case ${TARGETPLATFORM} in \
  "linux/arm64")  ARCHITECTURE=arm64  ;; \
  *)              ARCHITECTURE=amd64   ;; \
  esac \
  && echo "Installing terraform-docs v${tfdocsrelease} (${ARCHITECTURE})" \
  && wget https://github.com/terraform-docs/terraform-docs/releases/download/v${tfdocsrelease}/terraform-docs-v${tfdocsrelease}-linux-${ARCHITECTURE}.tar.gz \
  && tar -xzf terraform-docs-v${tfdocsrelease}-linux-${ARCHITECTURE}.tar.gz -C /usr/local/bin terraform-docs \
  && chmod +x /usr/local/bin/terraform-docs \
  && rm terraform-docs-v${tfdocsrelease}-linux-${ARCHITECTURE}.tar.gz

# Install Packer https://github.com/hashicorp/packer()
ARG packer_version=1.8.5
RUN case ${TARGETPLATFORM} in \
  "linux/arm64")  ARCHITECTURE=arm64  ;; \
  *)              ARCHITECTURE=amd64   ;; \
  esac \
  && echo "Installing packer v${packer_version} (${ARCHITECTURE})" \
  && wget -nv https://releases.hashicorp.com/packer/${packer_version}/packer_${packer_version}_linux_${ARCHITECTURE}.zip \
  && unzip -d /usr/local/bin packer_${packer_version}_linux_${ARCHITECTURE}.zip \
  && rm packer_${packer_version}_linux_${ARCHITECTURE}.zip

# Install hadolint (https://github.com/hadolint/hadolint)
ARG hadolint_version=2.12.0
RUN case ${TARGETPLATFORM} in \
  "linux/arm64")  ARCHITECTURE=arm64  ;; \
  *)              ARCHITECTURE=x86_64   ;; \
  esac \
  && echo "Installing hadolint v${hadolint_version} (${ARCHITECTURE})" \
  && wget -nv https://github.com/hadolint/hadolint/releases/download/v${hadolint_version}/hadolint-Linux-${ARCHITECTURE} \
  && mv hadolint-Linux-${ARCHITECTURE} /usr/local/bin/hadolint \
  && chmod +x /usr/local/bin/hadolint
