name: Test pull request

on:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]
    paths:
      - "Dockerfile/**"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  standard-alpine:
    name: standard-alpine-amd64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile/standard-alpine-amd64 --no-cache

      - uses: actions/checkout@v3
      - name: Docker Image Size
        run: docker inspect -f "{{ .Size }}" standard-alpine-amd64 | numfmt --to=si

  standard-ubuntu:
    name: standard-ubuntu-amd64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile/standard-ubuntu-amd64 --no-cache

      - uses: actions/checkout@v3
      - name: Docker Image Size
        run: docker inspect -f "{{ .Size }}" standard-ubuntu-amd64 | numfmt --to=si

  full-alpine:
    name: full-alpine-amd64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile/full-alpine-amd64 --no-cache

      - uses: actions/checkout@v3
      - name: Docker Image Size
        run: docker inspect -f "{{ .Size }}" full-alpine-amd64 | numfmt --to=si

  full-ubuntu:
    name: full-ubuntu-amd64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile/full-ubuntu-amd64 --no-cache

      - uses: actions/checkout@v3
      - name: Docker Image Size
        run: docker inspect -f "{{ .Size }}" full-ubuntu-amd64 | numfmt --to=si
